        bool status         # Статус сопоставлен столб или нет
        float32 azimuth     # Лидарные значения появляются при сопоставлении
        float32 hypotenuse 
        float32 distance_lidar
        float32 distance_laser
        float32 x_true      # Истинные значения задаются из топика
        float32 y_true 
        float32 theta_true1 
        float32 theta_true2 
        float32 x_lidar 
        float32 y_lidar 