SMwu vx          # Скорости линейная по х всех типов
SMwu vth         # Скорости угловая всех типов
SMwu dt          # Время между измерениями
float32 linRaw      # Сырые данные
float32 complX     # офсет во время стоянки
float32 flagAccel     # даные после применения bias
float32 pitch    # после фильтрации
float32 offsetX    # после слияния
float32 a_lin_X    # после слияния
float32 g_x    # после слияния
float32 a_lin_odom    # после слияния
float32 fused_accel    # после слияния
float32 odomVth    # после слияния
float32 offsetYaw    # после слияния
float32 complYaw    # после слияния
float32 fused_yaw    # после слияния
