SMwu vx          # Скорости линейная по х всех типов
SMwu vth         # Скорости угловая всех типов
SMwu dt          # Время между измерениями
float32 raw      # Сырые данные
float32 bias     # офсет во время стоянки
float32 data     # даные после применения bias
float32 filtr    # после фильтрации
float32 fused    # после слияния
float32 accOdom    # после слияния
float32 porog    # после слияния
