SPose modeDist
SPose modeAngle
SPose modeFused
int32 countFindPillar        #; // Колличество найденных столбов
int32 countComparePillar     #; // Колличество сопоставленных столбов
int32 countDistDirect       #; // Колличество сопоставленных столбов обединении разных методов
int32 countCrossCircle       #; // Количество пересечений окружностей при расчете по углам
float32 quality_ComparePillar # // Качество сопоставления столбов по сумме гипотенуз / кол-во столбов

SPose modeClaster

SPose mnkDist
SPose mnkAngle
SPose mnkFused
float32 quality_mknDist
float32 quality_mknAngle
float32 quality_mknFused

float32[4] azimut           #; // Индивидуальные углы на столбы