std_msgs/Header header
SSpi DriverData    # Все данные по обмену полученные из Driver
SSpi ModulData     # Все данные по обмену полученные из Modul
SSpi PrintData     # Все данные по обмену полученные из Modul
SSpi DataDriver    # Все данный по обмену отправленные из Data в Driver
SSpi DataModul     # Все данный по обмену отправленные из Data в Modul
SSpi DataPrint    # Все данный по обмену отправленные из Data в Driver