SPose modeDist
SPose modeAngle
SPose modeFused
int32 countMatchPillar        #; // Колличество сопоставленных столюов при расчете по растоянию
int32 countCrossCircle        #; // Количество пересечений окружностей при расчете по углам

SPose modeClaster

SPose mnkDist
SPose mnkAngle
SPose mnkFused
float32 quality_mknDist
float32 quality_mknAngle
float32 quality_mknFused

float32[4] azimut           #; // Индивидуальные углы на столбы